<?php
// This file is generated by AutoloadGenerator, do not adjust manually
// @codingStandardsIgnoreFile
global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'SmiteSpamAnalyzer' => __DIR__ . '/includes/SmiteSpamAnalyzer.php',
	'SmiteSpamApiQuery' => __DIR__ . '/api/SmiteSpamApiQuery.php',
	'SmiteSpamApiTrustUser' => __DIR__ . '/api/SmiteSpamApiTrustUser.php',
	'SmiteSpamExternalLinksChecker' => __DIR__ . '/includes/checkers/SmiteSpamExternalLinksChecker.php',
	'SmiteSpamHooks' => __DIR__ . '/SmiteSpam.hooks.php',
	'SmiteSpamRepeatedExternalLinksChecker' => __DIR__ . '/includes/checkers/SmiteSpamRepeatedExternalLinksChecker.php',
	'SmiteSpamWikiPage' => __DIR__ . '/includes/SmiteSpamWikiPage.php',
	'SmiteSpamWikitextChecker' => __DIR__ . '/includes/checkers/SmiteSpamWikitextChecker.php',
	'SpecialSmiteSpam' => __DIR__ . '/SpecialSmiteSpam.php',
	'SpecialSmiteSpamTrustedUsers' => __DIR__ . '/SpecialSmiteSpamTrustedUsers.php',
);
