<?php
// This file is generated by AutoloadGenerator, do not adjust manually
// @codingStandardsIgnoreFile
global $wgAutoloadClasses;

$wgAutoloadClasses += array(
	'SmiteSpamAnalyzer' => __DIR__ . '/includes/SmiteSpamAnalyzer.php',
	'SmiteSpamDeleter' => __DIR__ . '/includes/SmiteSpamDeleter.php',
	'SmiteSpamExternalLinksChecker' => __DIR__ . '/includes/checkers/SmiteSpamExternalLinksChecker.php',
	'SmiteSpamHeadingsChecker' => __DIR__ . '/includes/checkers/SmiteSpamHeadingsChecker.php',
	'SmiteSpamInternalLinksChecker' => __DIR__ . '/includes/checkers/SmiteSpamInternalLinksChecker.php',
	'SmiteSpamRepeatedExternalLinksChecker' => __DIR__ . '/includes/checkers/SmiteSpamRepeatedExternalLinksChecker.php',
	'SmiteSpamTemplatesChecker' => __DIR__ . '/includes/checkers/SmiteSpamTemplatesChecker.php',
	'SmiteSpamWikiPage' => __DIR__ . '/includes/SmiteSpamWikiPage.php',
	'SpecialSmiteSpam' => __DIR__ . '/SpecialSmiteSpam.php',
);
